### ISSUE TITLE
Neptune compatibility

### ISSUE THREAD

**Issue by bahador** [getzep/graphiti#110]
Hello. Forgive me for opening an issue for just a quick question. Is or will Graphiti be compatible with [AWS Neptune](https://docs.aws.amazon.com/neptune/latest/userguide/migration-compatibility.html)? I looked into [hosted Neo4j pricing](https://neo4j.com/pricing/) and it seems very steep. Thanks.

**Comment by danielchalef** [comment]
We've used openCypher whenever possible to enable future support of Neptune and other databases. Currently, Graphiti uses Neo4j's built-in BM25 and vector indexes. While Neptune can be configured to use OpenSearch and Neptune Analytics to enable similar functionality, deployment is significantly more complex. 

If you have experience with Neptune in such a configuration, we'd love your assistance with writing support for Neptune into Graphiti and documentation on configuring such a deployment. Let us know if this is of interest!

**Comment by bahador** [comment]
Thank you for the quick response. Unfortunately, I do not have that experience. But now knowing that, I'll try it out with Neo4j. Thanks again.

**Comment by davetbo-amzn** [comment]
@danielchalef if you ping me with details about the gap I would be happy to contribute. I could easily generalize this pattern I've been using to help you use Neptune Databases (preferable over Neptune Analytics for cost reasons) with whichever other vector index providers you support.

https://medium.com/@davetbo/graph-rag-part-2-adding-multi-tenancy-semantic-search-and-multi-context-retrieval-ee675b339c63
