### ISSUE TITLE
Build communities error

### ISSUE THREAD

**Issue by alejandrods** [getzep/graphiti#129]
Hello,

Running the [Podcast example](https://github.com/getzep/graphiti/blob/main/examples/podcast/podcast_runner.py#L76), it raises an error when it tries to build the communities:

```bash
neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureNotFound} {message: There is no procedure with the name `gds.graph.project` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.}
```

Any suggestion to fix it? Thank you!

**Comment by prasmussen15** [comment]
Hey! For community support you need to have neo4j's GraphDataScience plugin which can be found here: https://neo4j.com/docs/graph-data-science/current/installation/

I'm adding docs this morning for community stuff and I will make sure to add the graph data science plugin as a neo4j requirement on the README

**Comment by alejandrods** [comment]
Thanks!
