### ISSUE TITLE
Does Neo4J supports multi tenancy (Aura DB)

### ISSUE THREAD

**Issue by Anindyadeep** [getzep/graphiti#222]
Hi, I have been using Neo4J AuraDB, and one problem I see in GraphRAG is while we index more and more documents from different users it is hard to isolate them under the same instance. Now one way around is to put an unique user identifier inside `group_id` while doing indexing. However I wonder, if there is any sort of multi tenancy possible or not and can it be done using graphiti. 

Because I saw this problem while I tried to do it on Aura. [This issue](https://support.neo4j.com/s/article/360050567093-Unable-to-run-CREATE-DATABASE-or-DROP-DATABASE-commands-in-Aura)

**Comment by danielchalef** [comment]
Unfortunately, Graphiti does not offer multi-tenancy. As you mentioned, `group_id`s  may be used to create separate graphs.

**Comment by Anindyadeep** [comment]
I see, thanks for the information. I am closing this issue
