### ISSUE TITLE
Are the new edges generated by LLM being added which does not belong to the initial schema?

### ISSUE THREAD

**Issue by Anindyadeep** [getzep/graphiti#235]
Hi, while I was doing the upsert, I was getting this logs:

```
DEBUG     2024-12-09 16:37:16,028 graphiti_utils 221859 123380785688576 Created new edge: OPTED_FOR from (UUID: c49b31c6-ec2b-4b50-8c86-8fa6803a70c9) to (UUID: )
DEBUG     2024-12-09 16:37:16,028 graphiti_utils 221859 123380785688576 Created new edge: INTRODUCED from (UUID: a4b96d17-a70d-409d-938b-f29b918b16b3) to (UUID: )
DEBUG     2024-12-09 16:37:16,028 graphiti_utils 221859 123380785688576 Created new edge: CLAIMED from (UUID: 2887a13c-0a63-4af9-adf1-f617e24e47a5) to (UUID: )
DEBUG     2024-12-09 16:37:16,028 graphiti_utils 221859 123380785688576 Created new edge: PROPOSED from (UUID: 427291e6-b986-4534-ab11-7ac975e73c3b) to (UUID: )
DEBUG     2024-12-09 16:37:16,028 graphiti_utils 221859 123380785688576 Created new edge: INTRODUCED from (UUID: ae3ce336-80ef-4275-bd2d-32d8dbd45c08) to (UUID: )
[2024-12-09 16:37:16,864: INFO/ForkPoolWorker-14] HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
```

From what I understand, it comes from this part of the code `edge_ops.py`:

```python 
llm_response = await llm_client.generate_response(
        prompt_library.extract_edges.edge(context=context)
    )
    edges_data = llm_response.get('edges', [])
    context['extracted_facts'] = [
        edge_data.get('fact', '') for edge_data in edges_data
    ]
    edges = []
    for edge_data in edges_data:
        edge = EntityEdge(
            source_node_uuid=node_uuids_by_name_map.get(
                edge_data.get('source_entity_name', ''), ''
            ),
            target_node_uuid=node_uuids_by_name_map.get(
                edge_data.get('target_entity_name', ''), ''
            ),
            name=edge_data.get('relation_type', ''),
            group_id=group_id,
            fact=edge_data.get('fact', ''),
            episodes=[episode.uuid],
            created_at=datetime.now(timezone.utc),
            valid_at=None,
            invalid_at=None,
        )
        edges.append(edge)
        logger.debug(
            f'Created new edge: {edge.name} from (UUID: {edge.source_node_uuid}) to (UUID: {edge.target_node_uuid})'
        )
    return edges
```

However the final graph adheres to the schema which was created during the init (which consists of edge relations like `RELATES_TO`, `HAS_MEMBER`, `MENTIONED`. So I wonder, are these edges being converted to these three types (like convert it to the nearest edge type) or are they being discarded?

**Comment by danielchalef** [comment]
Hi @Anindyadeep - Graphiti has an internal ontology, with edge types named `RELATES_TO`, `HAS_MEMBER`, and `MENTIONED`. A semantic ontology is layered over this. For edges, the semantic edge value in the graph triple (such as `PROPOSED`) is persisted to the edge `name` field. Additionally, the plaintext value of the triple (node->edge->node) is persisted to an edge's `fact` field.

**Comment by Anindyadeep** [comment]
Ahh I see now, I missed seeing the `name` part which makes sense now. However (sorry I opened the issue after closing it), I have an additional question. Are those semantic edges utilized during the search (embedding / bm25 searches) or not?

**Comment by prasmussen15** [comment]
The rare used during BM25 search, but not semantic search. They can also be used for data visualization. In the future we plan to use the name field in other ways as well.

**Comment by Anindyadeep** [comment]
> The rare used during BM25 search, but not semantic search. They can also be used for data visualization. In the future we plan to use the name field in other ways as well.

Makes sense, thanks, now closing the issue.
